export enum IconType {
  Plus = 'fa-solid fa-plus',
  Phone = 'fa-solid fa-phone',
  Facebook = 'fa-brands fa-facebook-f',
  Messanger="fa-brands fa-facebook-messenger",
  Comments="fa-solid fa-message-lines",
  Instagram = 'fa-brands fa-instagram',
  YouTube = 'fa-brands fa-youtube',
  WhatsApp = 'fa-brands fa-square-whatsapp',
  Message = 'fa-solid fa-message',
  Comment = 'fa-solid fa-comment',
  Envelope = 'fa-solid fa-envelope',
  FileCheck = 'fa-solid fa-file-circle-check',
  Twitter ='fa-brands fa-x-twitter',
  User='fa-regular fa-user',
  Calendar='fa-regular fa-calendar-check',
  PenSquare='fa-regular fa-pen-to-square',
  ClockRotate='fa-solid fa-clock-rotate-left',
  File='fa-regular fa-file',
  Folder='fa-regular fa-folder',
  FileMagnifying='fa-regular fa-file-magnifying-glass'
}
